name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1.9.1
        with:
          title: $tag
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
